name: Build Crystal Reports Installer

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Display Repository Contents
      run: |
        echo "Repository contents:"
        Get-ChildItem -Path . -Recurse
      shell: pwsh  # Specify PowerShell

    - name: Restore NuGet Packages
      run: |
        if (Test-Path "WindowsFormsApp3/packages.config") {
          nuget restore WindowsFormsApp3/WindowsFormsApp3.sln
        } else {
          echo "No packages.config found, skipping restore"
        }
      shell: pwsh
      run:  |
        .\7zr.exe a -sfx "installer-output/TimeTableGenerator-Installer.exe" \
        "installer staging/*"
      shell: pwsh

    - name: Create Version Info
  # Create Version Info
      run: |
 `       $version = Get-Date -Format "yyyy.MM.dd"
        @"
        TimeTable Generator - Crystal Reports Application
        Version: $version
        Build Date: $(Get-Date)

        Files included in this installer:
        "@ | Out-File -FilePath "installer-output/Version-Info.txt"

        (Get-ChildItem -Path "installer staging") | Out-File -FilePath "installer-output/Version-Info.txt" -Append

        Get-Content -Path "installer-output/Version-Info.txt"
      shell: pwsh

        Get-Content -Path "installer-output/Version-Info.txt"
      shell: pwsh
